services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
