apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1 # Adjust based on your needs
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: aryarana/kafka:v1
          ports:
            - containerPort: 9092
          env:
            # - name: KAFKA_BROKER_ID
            #   value: "${POD_NAME}" # Dynamically set broker ID
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "" # Assuming a Zookeeper service named "zookeeper"
            - name: KAFKA_KRAFT_MODE
              value: "true" # For external access
            # - name: KAFKA_LISTENERS
            #   value: "PLAINTEXT://0.0.0.0:9092" # For internal communication
            # - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            #   value: "1"
            # - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
            #   value: "0"
      #     volumeMounts:
      #       - name: kafka-data
      #         mountPath: /var/lib/kafka

      # volumes:
      #   - name: kafka-data
      #     persistentVolumeClaim:
      #       claimName: kafka-data # Reference a PersistentVolumeClaim

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
